name: cure_team_1_update
description: A Flutter Clean Architecture project with BLoC (Cubit)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  connectivity_plus: ^7.0.0
  cross_file: ^0.3.5+1
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.7
  dio: ^5.9.0
  easy_date_timeline: ^2.0.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^8.2.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.5
  mobkit_dashed_border: ^0.0.8
  permission_handler: ^12.0.1
  pinput: ^6.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  device_preview: ^1.3.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sittings/
    - assets/images/profile/
    - assets/images/payment/

fonts:

  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
  - family: georgia
    fonts:
      - asset: assets/fonts/georgia.ttf
        weight: 400
  - family: PlusJakartaSans
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        weight: 400
  - family: Inter_28pt
    fonts:
      - asset: assets/fonts/Inter_28pt-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter_28pt-Medium.ttf
        weight: 500

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
  field_prefix: resource
  ignore_comments: true
